--1
INSERT INTO TB_CLASS_TYPE VALUES('01','전공필수');
INSERT INTO TB_CLASS_TYPE VALUES('02','전공선택');
INSERT INTO TB_CLASS_TYPE VALUES('03','교양필수');
INSERT INTO TB_CLASS_TYPE VALUES('04','교양선택');
INSERT INTO TB_CLASS_TYPE VALUES('05','논문지도');
COMMIT;
--2
CREATE TABLE TB_학생일반정보 AS SELECT * FROM VW_학생일반정보;
SELECT * FROM "TB_학생일반정보";
--3
CREATE TABLE TB_국어국문학과 AS
SELECT S.STUDENT_NO 학번, S.STUDENT_NAME 학생이름
        , TO_CHAR(TO_DATE(SUBSTR(S.STUDENT_SSN,1,2),'RR'),'YYYY') 출생년도
        , P.PROFESSOR_NAME 교수이름
    FROM TB_STUDENT S JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
    WHERE S.DEPARTMENT_NO = (SELECT D.DEPARTMENT_NO 
                                FROM TB_DEPARTMENT D 
                                WHERE D.DEPARTMENT_NAME = '국어국문학과')
;
SELECT * FROM TB_국어국문학과;
--4
SELECT * FROM TB_DEPARTMENT; -- 국어국문학과 정원 20이었음
UPDATE TB_DEPARTMENT SET CAPACITY = ROUND(CAPACITY*1.1,0);
SELECT * FROM TB_DEPARTMENT; -- 국어국문학과 정원 22로 바뀜
--5
UPDATE TB_STUDENT 
    SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
    WHERE STUDENT_NO = 'A413042'
;
SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A413042';
--6
UPDATE TB_STUDENT SET STUDENT_SSN = SUBSTR(STUDENT_SSN,1,6);
SELECT * FROM TB_STUDENT;
--7
UPDATE TB_GRADE G 
    SET G.POINT = 3.5 
    WHERE (G.STUDENT_NO,G.CLASS_NO) = (SELECT S.STUDENT_NO, C.CLASS_NO
                                            FROM TB_STUDENT S JOIN TB_CLASS C USING(DEPARTMENT_NO)
                                            WHERE S.STUDENT_NAME = '김명훈' 
                                            AND C.CLASS_NAME = '피부생리학')
;
SELECT * FROM TB_GRADE G WHERE (G.STUDENT_NO,G.CLASS_NO) = (SELECT S.STUDENT_NO, C.CLASS_NO
                                            FROM TB_STUDENT S JOIN TB_CLASS C USING(DEPARTMENT_NO)
                                            WHERE S.STUDENT_NAME = '김명훈' 
                                            AND C.CLASS_NAME = '피부생리학')
;
--8
SELECT COUNT(*) FROM TB_GRADE; -- 5036

SELECT COUNT(*)
    FROM TB_GRADE G
    WHERE G.STUDENT_NO IN (SELECT STUDENT_NO FROM TB_STUDENT WHERE ABSENCE_YN = 'Y')
; -- 483
DELETE TB_GRADE G 
    WHERE G.STUDENT_NO IN (SELECT STUDENT_NO 
                                FROM TB_STUDENT 
                                WHERE ABSENCE_YN = 'Y')
;
SELECT COUNT(*) FROM TB_GRADE; -- 4553
ROLLBACK;
