--1
DROP TABLE TB_CATEGORY;
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);
--2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);
--3
ALTER TABLE TB_CATEGORY ADD CONSTRAINT TC_NAME_PK PRIMARY KEY (NAME);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TB_CATEGORY';
--4
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

DESC TB_CLASS_TYPE;
--5
ALTER TABLE TB_CLASS_TYPE MODIFY (NAME VARCHAR2(20), NO VARCHAR(10));
ALTER TABLE TB_CATEGORY MODIFY (NAME VARCHAR2(20));
DESC TB_CATEGORY;
--6
ALTER TABLE TB_CATEGORY RENAME COLUMN  NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
DESC TB_CLASS_TYPE;
DESC TB_CATEGORY;
--7
--ALTER TABLE TB_CATEGORY RENAME CONSTRAINTS TC_NAME_PK TO PK_CATEGORY_NAME;
--ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINTS SYS_C007144 TO PK_CLASS_TYPE_NAME;
--8
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;
--9
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY 
                                FOREIGN KEY (CATEGORY) 
                                REFERENCES TB_CATEGORY(CATEGORY_NAME)
;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TB_DEPARTMENT';
--10
CREATE OR REPLACE VIEW VW_학생일반정보 AS
    SELECT STUDENT_NO 학번,STUDENT_NAME 학생이름,STUDENT_ADDRESS 주소 FROM TB_STUDENT
;
--11
CREATE OR REPLACE VIEW VW_지도면담 AS
SELECT S.STUDENT_NAME 학생이름,D.DEPARTMENT_NAME 학과이름,P.PROFESSOR_NAME 지도교수이름 
        FROM TB_STUDENT S JOIN TB_DEPARTMENT D USING(DEPARTMENT_NO)
                            LEFT JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
        ORDER BY 2
;
--12
CREATE OR REPLACE VIEW VW_학과별학생수 AS
SELECT D.DEPARTMENT_NAME 학과이름, COUNT(S.DEPARTMENT_NO) 학생수 
    FROM TB_STUDENT S JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
    GROUP BY D.DEPARTMENT_NAME
; 
--13
UPDATE VW_학생일반정보 SET 학생이름 = '권호민' WHERE 학번 = 'A213046';
COMMIT;
SELECT * FROM "VW_학생일반정보";
--14
CREATE OR REPLACE VIEW 뷰명 AS
    SELECT * FROM 테이블명
    WITH READ ONLY
;
--15
SELECT *
FROM(
SELECT C.CLASS_NO,C.CLASS_NAME, COUNT(G.STUDENT_NO)
    FROM TB_GRADE G JOIN TB_CLASS C ON G.CLASS_NO = C.CLASS_NO
    WHERE G.TERM_NO LIKE '2009%' OR G.TERM_NO LIKE '2008%'
                                OR G.TERM_NO LIKE '2007%'
    GROUP BY C.CLASS_NO, C.CLASS_NAME
    ORDER BY 3 DESC)
    WHERE ROWNUM <= 3
;
    